*\ Final project STAT448 Fall 23*\;
*\ Data set was obtained from the UCI Machine Learning Repository:
https://archive.ics.uci.edu/dataset/501/beijing+multi+site+air+quality+data *\;
*\This code read air quality data from location Guanyuan as an example *\; 
*\This code read air quality data from location Guanyuan as an example *\; 

*Loaded data;
data AirQualityT;
	infile '/home/u63566572/sasuser.v94/Tiantan.csv' dsd missover firstobs=2;
	input Rowno $ No year month day hour PM25 PM10 SO2 NO2 CO O3 TEMP PRES DEWP RAIN wd $ WSPM station $;
*\ Drop variables you do not need*\;
    drop Rowno station;   
run;
data AirQualityT2016;
  set AirQualityT;
  where year = 2016 and hour=12;
run;
*Categorical variables: month, year, day, hour, wd

*Question 1;

*MONTH CATEGORICAL VAR
*Analyzing TEMP with month;
proc anova data=AirQualityT;
	class month;
	model TEMP = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model TEMP = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing PRES with month;
proc anova data=AirQualityT;
	class month;
	model PRES = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PRES = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing PM25 with month;
proc anova data=AirQualityT;
	class month;
	model PM25 = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PM25 = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing PM10 with month;
proc anova data=AirQualityT;
	class month;
	model PM10 = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PM10 = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing SO2 with month;
proc anova data=AirQualityT;
	class month;
	model SO2 = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model SO2 = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing NO2 with month;
proc anova data=AirQualityT;
	class month;
	model NO2 = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model NO2 = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing CO with month;
proc anova data=AirQualityT;
	class month;
	model CO = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model CO = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing O3 with month;
proc anova data=AirQualityT;
	class month;
	model O3 = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model O3 = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing DEWP with month;
proc anova data=AirQualityT;
	class month;
	model DEWP = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model DEWP = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing RAIN with month;
proc anova data=AirQualityT;
	class month;
	model RAIN = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model RAIN = month;
  output out=diagnostics cookd= cd;
run;
*Analyzing WSMP with month;
proc anova data=AirQualityT;
	class month;
	model WSMP = month;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model WSMP = month;
  output out=diagnostics cookd= cd;
run;

*WD CATEGORICAL VAR
*Analyzing TEMP with wd;
proc anova data=AirQualityT;
	class wd;
	model TEMP = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model TEMP = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing PRES with wd;
proc anova data=AirQualityT;
	class wd;
	model PRES = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PRES = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing PM25 with wd;
proc anova data=AirQualityT;
	class wd;
	model PM25 = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PM25 = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing PM10 with wd;
proc anova data=AirQualityT;
	class wd;
	model PM10 = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model PM10 = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing SO2 with wd;
proc anova data=AirQualityT;
	class wd;
	model SO2 = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model SO2 = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing NO2 with wd;
proc anova data=AirQualityT;
	class wd;
	model NO2 = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model NO2 = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing CO with wd;
proc anova data=AirQualityT;
	class wd;
	model CO = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model CO = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing O3 with wd;
proc anova data=AirQualityT;
	class wd;
	model O3 = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model O3 = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing DEWP with wd;
proc anova data=AirQualityT;
	class wd;
	model DEWP = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model DEWP = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing RAIN with wd;
proc anova data=AirQualityT;
	class wd;
	model RAIN = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model RAIN = wd;
  output out=diagnostics cookd= cd;
run;
*Analyzing WSMP with wd;
proc anova data=AirQualityT;
	class wd;
	model WSMP = wd;
	ods select OverallANOVA FitStatistics ModelANOVA;
run;
proc reg data=AirQualityT;
  model WSMP = wd;
  output out=diagnostics cookd= cd;
run;


*Question 2;

*correlation coefficients between each of the pollutants (PM2.5, PM10, SO2, etc.) 
and the meteorological variables (Temperature, Pressure, Dew Point, Rain, Wind Speed);
proc corr data=AirQualityT;
	var PM25 PM10 SO2 NO2 CO O3;
	with TEMP PRES DEWP RAIN WSPM;
run;

*model with significant interactions for PM25;
proc reg data=AirQualityT;
	model PM25 = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model PM25 = TEMP DEWP RAIN WSPM / VIF;
run;

*model with significant interactions for PM10;
proc reg data=AirQualityT;
	model PM10 = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model PM10 = TEMP DEWP RAIN WSPM / VIF;
run;

*model with significant interactions for SO2;
proc reg data=AirQualityT;
	model SO2 = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model SO2 = TEMP DEWP RAIN WSPM / VIF;
run;

*model with significant interactions for NO2;
proc reg data=AirQualityT;
	model NO2 = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model NO2 = TEMP DEWP RAIN WSPM / VIF;
run;

*model with significant interactions for CO;
proc reg data=AirQualityT;
	model CO = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model CO = TEMP DEWP RAIN WSPM / VIF;
run;

*model with significant interactions for O3;
proc reg data=AirQualityT;
	model O3 = TEMP DEWP RAIN WSPM;
run;
*check for multicollinearity;
proc reg data=AirQualityT;
	model O3 = TEMP DEWP RAIN WSPM / VIF;
run;